services:
  sqlite:
    build:
      context: ./SQLite
      dockerfile: Dockerfile
    container_name: sqlite
    volumes:
      - sqlite-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - sqlite-data:/data
      - avatar-uploads:/app/uploads/avatars
      - ./backend:/app:rw
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - sqlite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - ./Game:/app/Game
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8443:8443"
    depends_on:
      - frontend
      - backend

volumes:
  sqlite-data:
    driver: local
  avatar-uploads:
    driver: local
